kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume1
  labels:
    type: local
spec:
  storageClassName: cdb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/cdb-vol1"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume2
  labels:
    type: local
spec:
  storageClassName: cdb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/cdb-vol2"
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: task-pv-volume3
  labels:
    type: local
spec:
  storageClassName: cdb-storage
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/local/cdb-vol3"